### ISSUE TITLE
Add banner so it's more clear where the tool starts.

### ISSUE THREAD

**Issue by JeroenKnoops** [philips-software/spdx-builder#17]
When we're using spdx-builder in f.e. https://github.com/philips-software/spdx-action it's a part of a chain of tools.

Please add a banner so we can see where spdx-builder starts.

An example of such banner is this one from OSS Reveiw Toolkit:
```
________ _____________________
\_____  \\______   \__    ___/ the OSS Review Toolkit, version 0.1.0-SNAPSHOT.
 /   |   \|       _/ |    |    Running 'analyze' under Java 11.0.8 on Linux with
/    |    \    |   \ |    |    ORT_CONFIG_DIR = /root/.ort/config
\_______  /____|_  / |____|    ORT_DATA_DIR = /root/.ort
        \/       \/
More environment variables:
JAVA_HOME = /opt/java/openjdk
ANDROID_HOME = /opt/android-sdk
GOPATH = /go
```

**Comment by timovandeput** [comment]
Added a banner in commit https://github.com/philips-software/spdx-builder/commit/6d0ae113f8efdbd61bb2866ec0ee59e4a49e9e93.
