### ISSUE TITLE
Create new version v0.5.0 with blackduck support

### ISSUE THREAD

**Issue by JeroenKnoops** [philips-software/spdx-builder#29]
SPDX-builder now supports blackduck as input. This is an experimental feature.

## Breaking change
Now we need to specify the source in the call.

`ort` for ORT input file
`blackduck` for blackduck input file

## Things to do

- [x] Update README with instructions how to use blackduck scanning.
- [x] Update README with updated ORT parameters.
- [x] Create v0.5.0

**Comment by JeroenKnoops** [comment]
Look in cli help for information what to put in README.

**Comment by timovandeput** [comment]
Updated README with instructions for extracting bill-of-materials from Black Duck, and modified the invocations for extracting a bill-of-materials from the ORT Analyzer output.

See commit https://github.com/philips-software/spdx-builder/commit/d774e28722d9bee1ab63e860a95db44f563a6eea.
