### ISSUE TITLE
Add yarn tree parser

### ISSUE THREAD

**Issue by JeroenKnoops** [philips-software/spdx-builder#41]
We have some projects which create a yarn list of dependencies with:

```
yarn licenses list
```

Lets add a tree parser for `yarn`.

## Example output:
```
yarn licenses v1.22.5
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
├─ (BSD-2-Clause OR MIT OR Apache-2.0)
│  └─ rc@1.2.8
│     ├─ URL: https://github.com/dominictarr/rc.git
│     ├─ VendorName: Dominic Tarr
│     └─ VendorUrl: dominictarr.com
├─ (MIT OR Apache-2.0)
│  └─ atob@2.1.2
│     ├─ URL: git://git.coolaj86.com/coolaj86/atob.js.git
│     ├─ VendorName: AJ ONeal
│     └─ VendorUrl: https://git.coolaj86.com/coolaj86/atob.js.git
├─ (MIT OR CC0-1.0)
│  ├─ type-fest@0.11.0
│  │  ├─ URL: https://github.com/sindresorhus/type-fest.git
│  │  ├─ VendorName: Sindre Sorhus
│  │  └─ VendorUrl: sindresorhus.com
│  ├─ type-fest@0.6.0
│  │  ├─ URL: https://github.com/sindresorhus/type-fest.git
│  │  ├─ VendorName: Sindre Sorhus
│  │  └─ VendorUrl: sindresorhus.com
│  └─ type-fest@0.8.1
│     ├─ URL: https://github.com/sindresorhus/type-fest.git
│     ├─ VendorName: Sindre Sorhus
│     └─ VendorUrl: sindresorhus.com
```

Maybe we need to use another yarn command to get a better list.

**Comment by JeroenKnoops** [comment]
@timovandeput This format is funky, grouped by license, but it looks like it takes the versions from the `yarn.lock` file.

**Comment by timovandeput** [comment]
Experimentation showed that pulling in dependencies with Yarn updates the `node_modules` tree according to the Yarn lock file, which NPM gladly accepts as "truth" in absence of a package lock file. This tree can be exported via the (existing) NPM tree route.

PS: It is fascinating to see that when the lock file is deleted, Yarn and NPM come up with different versions for the same transitive dependencies: NPM prefers a single version per package across the project, while Yarn prefers the "latest" version and therefore ends up with multiple versions of the same dependency.

**Comment by timovandeput** [comment]
After building using Yarn, the tree can be output using standard NPM tooling by (e.g.): `npm list --all --production`.
